"""add conversation_history to user_state

Revision ID: a4e6c9d2f758
Revises: f493c28060bd
Create Date: 2025-06-13 22:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON


# revision identifiers, used by Alembic.
revision = 'a4e6c9d2f758'
down_revision = 'f493c28060bd'  # Ajustar al valor de la última migración en tu sistema
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_states', sa.Column('conversation_history', JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_states', 'conversation_history')
    # ### end Alembic commands ###
