# .github/workflows/deploy-to-azure.yml

name: Build and Deploy to Azure Web App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  RESOURCE_GROUP: "beta-bot"
  ACR_NAME: "chat2025"
  WEBAPP_NAME: "chat-app-4313"
  DOCKER_IMAGE_NAME: "whatsapp-bot-image" # Nombre de la imagen en ACR

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker image to ACR
        id: build-image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build . -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          # --- CORRECCIÓN: Se usa 'resource-group-name' en lugar de 'resource-group' ---
          resource-group-name: ${{ env.RESOURCE_GROUP }}
          images: '${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.build-image.outputs.image-tag }}'
          
      - name: Logout from Azure
        if: always()
        run: |
          echo "Logging out from Azure..."
          az logout && az cache purge && az account clear