name: Build and Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  RESOURCE_GROUP: whatsapp-bot-rg
  ACR_NAME: whatsappbotacr  # Reemplaza con tu ACR_NAME
  WEBAPP_NAME: whatsapp-bot  # Reemplaza con tu WEBAPP_NAME
  DOCKER_IMAGE: whatsapp-bot-image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push image to ACR
      run: |
        # Obtener el SHA del commit para etiquetar la imagen
        IMAGE_TAG=$(git rev-parse --short HEAD)
        
        # Construir la imagen
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE }}:$IMAGE_TAG .
        
        # Subir la imagen
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE }}:$IMAGE_TAG
        
        # Guardar el tag para el siguiente paso
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}
        images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}

    - name: Update Web App Settings
      run: |
        # Actualizar la configuración de la Web App
        az webapp config appsettings set \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.WEBAPP_NAME }} \
          --settings \
            DOCKER_REGISTRY_SERVER_URL=https://${{ env.ACR_NAME }}.azurecr.io \
            DOCKER_REGISTRY_SERVER_USERNAME=${{ secrets.ACR_USERNAME }} \
            DOCKER_REGISTRY_SERVER_PASSWORD=${{ secrets.ACR_PASSWORD }} \
            WEBSITES_PORT=8000

    - name: Verify deployment
      run: |
        echo "Verificando despliegue..."
        curl -s https://${{ env.WEBAPP_NAME }}.azurewebsites.net/api/health