# Nombre del Workflow
name: Build and Deploy to Azure Web App

# Disparadores (Triggers)
on:
  # Se activa en cada push a la rama 'master' (tu rama principal)
  push:
    branches: [ "master" ]
  # Permite ejecutarlo manualmente desde la interfaz de GitHub
  workflow_dispatch:

# Variables de Entorno Globales para el Workflow
env:
  RESOURCE_GROUP: "beta-bot"
  ACR_NAME: "chat2025"
  WEBAPP_NAME: "chat-app-4313"
  DOCKER_IMAGE_NAME: "whatsapp-bot-image" # Nombre de la imagen en ACR

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker image to ACR
        run: |
          # Usamos el SHA del commit para una etiqueta de imagen única e inmutable
          IMAGE_TAG=${{ github.sha }}
          
          # Construimos y subimos la imagen en un solo paso
          docker build . -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          # El grupo de recursos es útil pero no estrictamente necesario si el app-name es único.
          # Lo dejamos por claridad.
          resource-group: ${{ env.RESOURCE_GROUP }}
          images: '${{ env.ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}'

      - name: Logout from Azure
        if: always() # Este paso se ejecuta siempre, incluso si los anteriores fallan.
        run: |
          echo "Logging out from Azure..."
          az logout
          az cache purge
          az account clear